### PR TITLE
add DPDK compile commands to Makefile.in

### PR DESCRIPTION
**Pull request by lzskyline**
without the fix in src/Makefile.in I am not able compile the Suricata Binary.

### CODE REVIEW

**Comment by lzskyline** [comment]
image
CCLD     suricata
undefined reference to TmModuleReceiveDpdkRegister
undefined reference to TmModuleDecodeDpdkRegister

**Comment by vipinpv85** [comment]
As you can already see in the branch I have these changes done before 

```
ls -lrtha suricata-4.1.4/src/Makefile.in
-rw-r--r-- 1 root root 95K Jun 26 23:40 suricata-4.1.4/src/Makefile.in
```

```
diff --git a/suricata-4.1.4/src/Makefile.in b/suricata-4.1.4/src/Makefile.in
index 500f24d..0378ed6 100644
--- a/suricata-4.1.4/src/Makefile.in
+++ b/suricata-4.1.4/src/Makefile.in
@@ -308,12 +308,12 @@ am_suricata_OBJECTS = alert-debuglog.$(OBJEXT) alert-fastlog.$(OBJEXT) \
        source-pcap.$(OBJEXT) source-pcap-file.$(OBJEXT) \
        source-pcap-file-directory-helper.$(OBJEXT) \
        source-pcap-file-helper.$(OBJEXT) source-pfring.$(OBJEXT) \
-       source-windivert.$(OBJEXT) stream.$(OBJEXT) \
-       stream-tcp.$(OBJEXT) stream-tcp-inline.$(OBJEXT) \
-       stream-tcp-list.$(OBJEXT) stream-tcp-reassemble.$(OBJEXT) \
-       stream-tcp-sack.$(OBJEXT) stream-tcp-util.$(OBJEXT) \
-       suricata.$(OBJEXT) threads.$(OBJEXT) tm-modules.$(OBJEXT) \
-       tmqh-flow.$(OBJEXT) tmqh-nfq.$(OBJEXT) \
+       source-windivert.$(OBJEXT) source-dpdk.$(OBJEXT) \
+       stream.$(OBJEXT) stream-tcp.$(OBJEXT) \
+       stream-tcp-inline.$(OBJEXT) stream-tcp-list.$(OBJEXT) \
+       stream-tcp-reassemble.$(OBJEXT) stream-tcp-sack.$(OBJEXT) \
+       stream-tcp-util.$(OBJEXT) suricata.$(OBJEXT) threads.$(OBJEXT) \
+       tm-modules.$(OBJEXT) tmqh-flow.$(OBJEXT) tmqh-nfq.$(OBJEXT) \
        tmqh-packetpool.$(OBJEXT) tmqh-simple.$(OBJEXT) \
        tm-queuehandlers.$(OBJEXT) tm-queues.$(OBJEXT) \
        tm-threads.$(OBJEXT) unix-manager.$(OBJEXT) \
@@ -1028,6 +1028,7 @@ source-pcap-file-directory-helper.c source-pcap-file-directory-helper.h \
 source-pcap-file-helper.c source-pcap-file-helper.h \
 source-pfring.c source-pfring.h \
 source-windivert.c source-windivert.h \
+source-dpdk.c source-dpdk.h \
 stream.c stream.h \
 stream-tcp.c stream-tcp.h stream-tcp-private.h \
 stream-tcp-inline.c stream-tcp-inline.h \
@@ -1170,8 +1171,8 @@ EXTRA_DIST = tests
 AM_CPPFLAGS = $(all_includes)

 # the library search path.
+       stream.$(OBJEXT) stream-tcp.$(OBJEXT) \
+       stream-tcp-inline.$(OBJEXT) stream-tcp-list.$(OBJEXT) \
+       stream-tcp-reassemble.$(OBJEXT) stream-tcp-sack.$(OBJEXT) \
+       stream-tcp-util.$(OBJEXT) suricata.$(OBJEXT) threads.$(OBJEXT) \
+       tm-modules.$(OBJEXT) tmqh-flow.$(OBJEXT) tmqh-nfq.$(OBJEXT) \
        tmqh-packetpool.$(OBJEXT) tmqh-simple.$(OBJEXT) \
        tm-queuehandlers.$(OBJEXT) tm-queues.$(OBJEXT) \
        tm-threads.$(OBJEXT) unix-manager.$(OBJEXT) \
@@ -1028,6 +1028,7 @@ source-pcap-file-directory-helper.c source-pcap-file-directory-helper.h \
 source-pcap-file-helper.c source-pcap-file-helper.h \
 source-pfring.c source-pfring.h \
 source-windivert.c source-windivert.h \
+source-dpdk.c source-dpdk.h \
 stream.c stream.h \
 stream-tcp.c stream-tcp.h stream-tcp-private.h \
 stream-tcp-inline.c stream-tcp-inline.h \
@@ -1170,8 +1171,8 @@ EXTRA_DIST = tests
 AM_CPPFLAGS = $(all_includes)

 # the library search path.
-suricata_LDFLAGS = $(all_libraries) ${SECLDFLAGS}
-suricata_LDADD = $(HTP_LDADD) $(RUST_LDADD) ${DPDK_LDFLAGS}
+suricata_LDFLAGS = $(all_libraries) ${SECLDFLAGS} ${DPDK_LDFLAGS}
+suricata_LDADD = $(HTP_LDADD) $(RUST_LDADD)
 @HAVE_RUST_TRUE@suricata_DEPENDENCIES = $(RUST_SURICATA_LIB)

 # default CFLAGS
@@ -1635,6 +1636,7 @@ distclean-compile:
 @AMDEP_TRUE@@am__include@ @am__quote@./$(DEPDIR)/runmode-windivert.Po@am__quote@
 @AMDEP_TRUE@@am__include@ @am__quote@./$(DEPDIR)/runmodes.Po@am__quote@
 @AMDEP_TRUE@@am__include@ @am__quote@./$(DEPDIR)/source-af-packet.Po@am__quote@
+@AMDEP_TRUE@@am__include@ @am__quote@./$(DEPDIR)/source-dpdk.Po@am__quote@
 @AMDEP_TRUE@@am__include@ @am__quote@./$(DEPDIR)/source-erf-dag.Po@am__quote@
 @AMDEP_TRUE@@am__include@ @am__quote@./$(DEPDIR)/source-erf-file.Po@am__quote@
 @AMDEP_TRUE@@am__include@ @am__quote@./$(DEPDIR)/source-ipfw.Po@am__quote@
```

hence humbly requesting for an explanation for the statement `source-dpdk.o would not have been compiled before and I fixed `.

**Comment by lzskyline** [comment]
> As you can already see in the branch I have these changes done before
> 
> ```
> ls -lrtha suricata-4.1.4/src/Makefile.in
> -rw-r--r-- 1 root root 95K Jun 26 23:40 suricata-4.1.4/src/Makefile.in
> ```
> 
> ```
> diff --git a/suricata-4.1.4/src/Makefile.in b/suricata-4.1.4/src/Makefile.in
> index 500f24d..0378ed6 100644
> --- a/suricata-4.1.4/src/Makefile.in
> +++ b/suricata-4.1.4/src/Makefile.in
> @@ -308,12 +308,12 @@ am_suricata_OBJECTS = alert-debuglog.$(OBJEXT) alert-fastlog.$(OBJEXT) \
>         source-pcap.$(OBJEXT) source-pcap-file.$(OBJEXT) \
>         source-pcap-file-directory-helper.$(OBJEXT) \
>         source-pcap-file-helper.$(OBJEXT) source-pfring.$(OBJEXT) \
> -       source-windivert.$(OBJEXT) stream.$(OBJEXT) \
> -       stream-tcp.$(OBJEXT) stream-tcp-inline.$(OBJEXT) \
> -       stream-tcp-list.$(OBJEXT) stream-tcp-reassemble.$(OBJEXT) \
> -       stream-tcp-sack.$(OBJEXT) stream-tcp-util.$(OBJEXT) \
> -       suricata.$(OBJEXT) threads.$(OBJEXT) tm-modules.$(OBJEXT) \
> -       tmqh-flow.$(OBJEXT) tmqh-nfq.$(OBJEXT) \
> +       source-windivert.$(OBJEXT) source-dpdk.$(OBJEXT) \
> +       stream.$(OBJEXT) stream-tcp.$(OBJEXT) \
> +       stream-tcp-inline.$(OBJEXT) stream-tcp-list.$(OBJEXT) \
> +       stream-tcp-reassemble.$(OBJEXT) stream-tcp-sack.$(OBJEXT) \
> +       stream-tcp-util.$(OBJEXT) suricata.$(OBJEXT) threads.$(OBJEXT) \
> +       tm-modules.$(OBJEXT) tmqh-flow.$(OBJEXT) tmqh-nfq.$(OBJEXT) \
>         tmqh-packetpool.$(OBJEXT) tmqh-simple.$(OBJEXT) \
>         tm-queuehandlers.$(OBJEXT) tm-queues.$(OBJEXT) \
>         tm-threads.$(OBJEXT) unix-manager.$(OBJEXT) \
> @@ -1028,6 +1028,7 @@ source-pcap-file-directory-helper.c source-pcap-file-directory-helper.h \
>  source-pcap-file-helper.c source-pcap-file-helper.h \
>  source-pfring.c source-pfring.h \
>  source-windivert.c source-windivert.h \
> +source-dpdk.c source-dpdk.h \
>  stream.c stream.h \
>  stream-tcp.c stream-tcp.h stream-tcp-private.h \
>  stream-tcp-inline.c stream-tcp-inline.h \
> @@ -1170,8 +1171,8 @@ EXTRA_DIST = tests
>  AM_CPPFLAGS = $(all_includes)
> 
>  # the library search path.
> +       stream.$(OBJEXT) stream-tcp.$(OBJEXT) \
> +       stream-tcp-inline.$(OBJEXT) stream-tcp-list.$(OBJEXT) \
> +       stream-tcp-reassemble.$(OBJEXT) stream-tcp-sack.$(OBJEXT) \
> +       stream-tcp-util.$(OBJEXT) suricata.$(OBJEXT) threads.$(OBJEXT) \
> +       tm-modules.$(OBJEXT) tmqh-flow.$(OBJEXT) tmqh-nfq.$(OBJEXT) \
>         tmqh-packetpool.$(OBJEXT) tmqh-simple.$(OBJEXT) \
>         tm-queuehandlers.$(OBJEXT) tm-queues.$(OBJEXT) \
>         tm-threads.$(OBJEXT) unix-manager.$(OBJEXT) \
> @@ -1028,6 +1028,7 @@ source-pcap-file-directory-helper.c source-pcap-file-directory-helper.h \
>  source-pcap-file-helper.c source-pcap-file-helper.h \
>  source-pfring.c source-pfring.h \
>  source-windivert.c source-windivert.h \
> +source-dpdk.c source-dpdk.h \
>  stream.c stream.h \
>  stream-tcp.c stream-tcp.h stream-tcp-private.h \
>  stream-tcp-inline.c stream-tcp-inline.h \
> @@ -1170,8 +1171,8 @@ EXTRA_DIST = tests
>  AM_CPPFLAGS = $(all_includes)
> 
>  # the library search path.
> -suricata_LDFLAGS = $(all_libraries) ${SECLDFLAGS}
> -suricata_LDADD = $(HTP_LDADD) $(RUST_LDADD) ${DPDK_LDFLAGS}
> +suricata_LDFLAGS = $(all_libraries) ${SECLDFLAGS} ${DPDK_LDFLAGS}
> +suricata_LDADD = $(HTP_LDADD) $(RUST_LDADD)
>  @HAVE_RUST_TRUE@suricata_DEPENDENCIES = $(RUST_SURICATA_LIB)
> 
>  # default CFLAGS
> @@ -1635,6 +1636,7 @@ distclean-compile:
>  @AMDEP_TRUE@@am__include@ @am__quote@./$(DEPDIR)/runmode-windivert.Po@am__quote@
>  @AMDEP_TRUE@@am__include@ @am__quote@./$(DEPDIR)/runmodes.Po@am__quote@
>  @AMDEP_TRUE@@am__include@ @am__quote@./$(DEPDIR)/source-af-packet.Po@am__quote@
> +@AMDEP_TRUE@@am__include@ @am__quote@./$(DEPDIR)/source-dpdk.Po@am__quote@
>  @AMDEP_TRUE@@am__include@ @am__quote@./$(DEPDIR)/source-erf-dag.Po@am__quote@
>  @AMDEP_TRUE@@am__include@ @am__quote@./$(DEPDIR)/source-erf-file.Po@am__quote@
>  @AMDEP_TRUE@@am__include@ @am__quote@./$(DEPDIR)/source-ipfw.Po@am__quote@
> ```
> 
> hence humbly requesting for an explanation for the statement `source-dpdk.o would not have been compiled before and I fixed `.

Emmm. I didn't see the code you mentioned on the master branch,

**Comment by vipinpv85** [comment]
> > As you can already see in the branch I have these changes done before
> > ```
> > ls -lrtha suricata-4.1.4/src/Makefile.in
> > -rw-r--r-- 1 root root 95K Jun 26 23:40 suricata-4.1.4/src/Makefile.in
> > ```
> > 
> > 
> > ```
> > diff --git a/suricata-4.1.4/src/Makefile.in b/suricata-4.1.4/src/Makefile.in
> > index 500f24d..0378ed6 100644
> > --- a/suricata-4.1.4/src/Makefile.in
> > +++ b/suricata-4.1.4/src/Makefile.in
> > @@ -308,12 +308,12 @@ am_suricata_OBJECTS = alert-debuglog.$(OBJEXT) alert-fastlog.$(OBJEXT) \
> >         source-pcap.$(OBJEXT) source-pcap-file.$(OBJEXT) \
> >         source-pcap-file-directory-helper.$(OBJEXT) \
> >         source-pcap-file-helper.$(OBJEXT) source-pfring.$(OBJEXT) \
> > -       source-windivert.$(OBJEXT) stream.$(OBJEXT) \
> > -       stream-tcp.$(OBJEXT) stream-tcp-inline.$(OBJEXT) \
> > -       stream-tcp-list.$(OBJEXT) stream-tcp-reassemble.$(OBJEXT) \
> > -       stream-tcp-sack.$(OBJEXT) stream-tcp-util.$(OBJEXT) \
> > -       suricata.$(OBJEXT) threads.$(OBJEXT) tm-modules.$(OBJEXT) \
> > -       tmqh-flow.$(OBJEXT) tmqh-nfq.$(OBJEXT) \
> > +       source-windivert.$(OBJEXT) source-dpdk.$(OBJEXT) \
> > +       stream.$(OBJEXT) stream-tcp.$(OBJEXT) \
> > +       stream-tcp-inline.$(OBJEXT) stream-tcp-list.$(OBJEXT) \
> > +       stream-tcp-reassemble.$(OBJEXT) stream-tcp-sack.$(OBJEXT) \
> > +       stream-tcp-util.$(OBJEXT) suricata.$(OBJEXT) threads.$(OBJEXT) \
> > +       tm-modules.$(OBJEXT) tmqh-flow.$(OBJEXT) tmqh-nfq.$(OBJEXT) \
> >         tmqh-packetpool.$(OBJEXT) tmqh-simple.$(OBJEXT) \
> >         tm-queuehandlers.$(OBJEXT) tm-queues.$(OBJEXT) \
> >         tm-threads.$(OBJEXT) unix-manager.$(OBJEXT) \
> > @@ -1028,6 +1028,7 @@ source-pcap-file-directory-helper.c source-pcap-file-directory-helper.h \
> >  source-pcap-file-helper.c source-pcap-file-helper.h \
> >  source-pfring.c source-pfring.h \
> >  source-windivert.c source-windivert.h \
> > +source-dpdk.c source-dpdk.h \
> >  stream.c stream.h \
> >  stream-tcp.c stream-tcp.h stream-tcp-private.h \
> >  stream-tcp-inline.c stream-tcp-inline.h \
> > @@ -1170,8 +1171,8 @@ EXTRA_DIST = tests
> >  AM_CPPFLAGS = $(all_includes)
> > 
> >  # the library search path.
> > +       stream.$(OBJEXT) stream-tcp.$(OBJEXT) \
> > +       stream-tcp-inline.$(OBJEXT) stream-tcp-list.$(OBJEXT) \
> > +       stream-tcp-reassemble.$(OBJEXT) stream-tcp-sack.$(OBJEXT) \
> > +       stream-tcp-util.$(OBJEXT) suricata.$(OBJEXT) threads.$(OBJEXT) \
> > +       tm-modules.$(OBJEXT) tmqh-flow.$(OBJEXT) tmqh-nfq.$(OBJEXT) \
> >         tmqh-packetpool.$(OBJEXT) tmqh-simple.$(OBJEXT) \
> >         tm-queuehandlers.$(OBJEXT) tm-queues.$(OBJEXT) \
> >         tm-threads.$(OBJEXT) unix-manager.$(OBJEXT) \
> > @@ -1028,6 +1028,7 @@ source-pcap-file-directory-helper.c source-pcap-file-directory-helper.h \
> >  source-pcap-file-helper.c source-pcap-file-helper.h \
> >  source-pfring.c source-pfring.h \
> >  source-windivert.c source-windivert.h \
> > +source-dpdk.c source-dpdk.h \
> >  stream.c stream.h \
> >  stream-tcp.c stream-tcp.h stream-tcp-private.h \
> >  stream-tcp-inline.c stream-tcp-inline.h \
> > @@ -1170,8 +1171,8 @@ EXTRA_DIST = tests
> >  AM_CPPFLAGS = $(all_includes)
> > 
> >  # the library search path.
> > -suricata_LDFLAGS = $(all_libraries) ${SECLDFLAGS}
> > -suricata_LDADD = $(HTP_LDADD) $(RUST_LDADD) ${DPDK_LDFLAGS}
> > +suricata_LDFLAGS = $(all_libraries) ${SECLDFLAGS} ${DPDK_LDFLAGS}
> > +suricata_LDADD = $(HTP_LDADD) $(RUST_LDADD)
> >  @HAVE_RUST_TRUE@suricata_DEPENDENCIES = $(RUST_SURICATA_LIB)
> > 
> >  # default CFLAGS
> > @@ -1635,6 +1636,7 @@ distclean-compile:
> >  @AMDEP_TRUE@@am__include@ @am__quote@./$(DEPDIR)/runmode-windivert.Po@am__quote@
> >  @AMDEP_TRUE@@am__include@ @am__quote@./$(DEPDIR)/runmodes.Po@am__quote@
> >  @AMDEP_TRUE@@am__include@ @am__quote@./$(DEPDIR)/source-af-packet.Po@am__quote@
> > +@AMDEP_TRUE@@am__include@ @am__quote@./$(DEPDIR)/source-dpdk.Po@am__quote@
> >  @AMDEP_TRUE@@am__include@ @am__quote@./$(DEPDIR)/source-erf-dag.Po@am__quote@
> >  @AMDEP_TRUE@@am__include@ @am__quote@./$(DEPDIR)/source-erf-file.Po@am__quote@
> >  @AMDEP_TRUE@@am__include@ @am__quote@./$(DEPDIR)/source-ipfw.Po@am__quote@
> > ```
> > 
> > 
> > hence humbly requesting for an explanation for the statement `source-dpdk.o would not have been compiled before and I fixed `.
> 
> Emmm. I didn't see the code you mentioned on the master branch,

since it is not committed to `remote origin`. But please explain your statement `ource-dpdk.o would not have been compiled before and I fixed `

**Comment by lzskyline** [comment]
https://raw.githubusercontent.com/vipinpv85/DPDK_SURICATA-4_1_1/master/suricata-4.1.4/src/Makefile.in

image

**Comment by vipinpv85** [comment]
> https://raw.githubusercontent.com/vipinpv85/DPDK_SURICATA-4_1_1/master/suricata-4.1.4/src/Makefile.in
> 
> image

please explain what is that you are trying to say? As per my current understanding `I have changes in my local branch which is not pushed to master origin branch. There has been no prior communication between us on the same too.` 

So humbly requesting you please explain.

**Comment by lzskyline** [comment]
The "source-dpdk.*" file is not added to the "Makefile.in" file, so it is not compiled by GCC, therefore the "source-dpdk.o" file is not generated.
And the CCLD Suricata command failed to execute and prompted that the file could not be found.
I fixed this problem by modifying the makefile.in file

**Comment by vipinpv85** [comment]
> The "source-dpdk.*" file is not added to the "Makefile.in" file, so it is not compiled by GCC, therefore the "source-dpdk.o" file is not generated.
> And the CCLD Suricata command failed to execute and prompted that the file could not be found.
> I fixed this problem by modifying the makefile.in file

I have already communicated to in the above comments `I have changes in my local branch which is not pushed to master origin branch. There has been no prior communication between us on the same too`. 

Is your question `without the fix in src/Makefile.in I am not able compile the Suricata Binary?` and your pull request to fix this?

**Comment by lzskyline** [comment]
Yes

**Comment by lzskyline** [comment]
I didn't know the issue had been fixed, so I committed this commit. Now you can close it :)

**Comment by vipinpv85** [comment]
> Yes

superb, now we are aligned. Thanks for trying and suggesting the fix. This looks good. I am happy to merge your changes if you can resend with couple of corrections

1.  commit message should highlight the changes and reason. example `Makefile: add compiler link and clean to source-dpdk.o`
2. commit message should have author signoff message.
3. please add `source-dpdk.$(OBJEXT)` at end or group as shared in my patch
4. please add `source-dpdk.c source-dpdk.h`  at end of group as shared in my patch
5. please add `@AMDEP_TRUE@@am__include@ @am__quote@./$(DEPDIR)/source-dpdk.Po@am__quote@` end of group.

and please resend the merge request. I am happy to accept.

**Comment by vipinpv85** [comment]
> I didn't know the issue had been fixed, so I committed this commit. Now you can close it :)

I will wait for your corrected Pull request to merge as you author for the fix. If  you are not sharing, please let me know too.

**Comment by lzskyline** [comment]
thanks for your advice, but I haven't done things like this before, and I'm not good at English, so I don't quite understand what your means: "at end or group as Shared in my patch".

**Comment by lzskyline** [comment]
Do you mean to create a patch file instead of directly changing the Makefile.in file?

**Comment by vipinpv85** [comment]
> thanks for your advice, but I haven't done things like this before, and I'm not good at English, so I don't quite understand what your means: "at end or group as Shared in my patch".

Since we are adding a new file, let us add it in end of group. Example

```
 304         source-erf-dag.$(OBJEXT) source-erf-file.$(OBJEXT) \
 305         source-ipfw.$(OBJEXT) source-mpipe.$(OBJEXT) \
 306         source-napatech.$(OBJEXT) source-netmap.$(OBJEXT) \
 307         source-nfq.$(OBJEXT) source-nflog.$(OBJEXT) \
 308         source-pcap.$(OBJEXT) source-pcap-file.$(OBJEXT) \
 309         source-pcap-file-directory-helper.$(OBJEXT) \
 310         source-pcap-file-helper.$(OBJEXT) source-pfring.$(OBJEXT) \
 311         source-windivert.$(OBJEXT) source-dpdk.$(OBJEXT) \
```
and

```
1016 source-af-packet.c source-af-packet.h \
1017 source-erf-dag.c source-erf-dag.h \
1018 source-erf-file.c source-erf-file.h \
1019 source-ipfw.c source-ipfw.h \
1020 source-mpipe.c source-mpipe.h \
1021 source-napatech.c source-napatech.h \
1022 source-netmap.c source-netmap.h \
1023 source-nfq.c source-nfq.h \
1024 source-nflog.c source-nflog.h \
1025 source-pcap.c source-pcap.h \
1026 source-pcap-file.c source-pcap-file.h \
1027 source-pcap-file-directory-helper.c source-pcap-file-directory-helper.h \
1028 source-pcap-file-helper.c source-pcap-file-helper.h \
1029 source-pfring.c source-pfring.h \
1030 source-windivert.c source-windivert.h \
1031 source-dpdk.c source-dpdk.h \
```

and

```
1638 @AMDEP_TRUE@@am__include@ @am__quote@./$(DEPDIR)/source-af-packet.Po@am__quote@
1639 @AMDEP_TRUE@@am__include@ @am__quote@./$(DEPDIR)/source-erf-dag.Po@am__quote@
1640 @AMDEP_TRUE@@am__include@ @am__quote@./$(DEPDIR)/source-erf-file.Po@am__quote@
1641 @AMDEP_TRUE@@am__include@ @am__quote@./$(DEPDIR)/source-ipfw.Po@am__quote@
1642 @AMDEP_TRUE@@am__include@ @am__quote@./$(DEPDIR)/source-mpipe.Po@am__quote@
1643 @AMDEP_TRUE@@am__include@ @am__quote@./$(DEPDIR)/source-napatech.Po@am__quote@
1644 @AMDEP_TRUE@@am__include@ @am__quote@./$(DEPDIR)/source-netmap.Po@am__quote@
1645 @AMDEP_TRUE@@am__include@ @am__quote@./$(DEPDIR)/source-nflog.Po@am__quote@
1646 @AMDEP_TRUE@@am__include@ @am__quote@./$(DEPDIR)/source-nfq.Po@am__quote@
1647 @AMDEP_TRUE@@am__include@ @am__quote@./$(DEPDIR)/source-pcap-file-directory-helper.Po@am__quote@
1648 @AMDEP_TRUE@@am__include@ @am__quote@./$(DEPDIR)/source-pcap-file-helper.Po@am__quote@
1649 @AMDEP_TRUE@@am__include@ @am__quote@./$(DEPDIR)/source-pcap-file.Po@am__quote@
1650 @AMDEP_TRUE@@am__include@ @am__quote@./$(DEPDIR)/source-pcap.Po@am__quote@
1651 @AMDEP_TRUE@@am__include@ @am__quote@./$(DEPDIR)/source-pfring.Po@am__quote@
1652 @AMDEP_TRUE@@am__include@ @am__quote@./$(DEPDIR)/source-windivert.Po@am__quote@
1653 @AMDEP_TRUE@@am__include@ @am__quote@./$(DEPDIR)/source-dpdk.Po@am__quote@
```

note: I am not native English speaker too.

**Comment by lzskyline** [comment]
Thank you for your kindness and patience. I will correct and resend as soon as possible :)

**Pull request merged**
